
upstream video-tube-backend-api-server {
    server video-tube-backend-api-server-1:8000;
    # server video-tube-backend-api-server-2:8000;
}

server {
    listen 80;
    server_name localhost;


    location / {
        proxy_pass http://video-tube-frontend:3000;
    }

    location /api/ {
        proxy_pass http://video-tube-backend-api-server/;
    }

    location /static/ {
        alias /app/static/;
    }
}
