
upstream video-tube-backend-api-server {
    server video-tube-backend-api-server-1:8000;
    # server video-tube-backend-api-server-2:8000;
}

server {
    listen 80;
    server_name localhost;


    location / {
        proxy_pass http://video-tube-frontend:3000;
    }

    location /api/ {
        proxy_pass http://video-tube-backend-api-server/;
    }

    location /socket.io/ {
        # if we end with a slash, it will add the path to the end of the url, so we need to remove it
        # proxy_pass http://video-tube-backend-api-server/; --- IGNORE ---
        proxy_pass http://video-tube-backend-api-server;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /static/ {
        alias /app/static/;
    }
}
